#!/usr/bin/env bash
#
# One-command setup for a fresh clone.
#
#   bash tool/bootstrap.sh
#
# This repo intentionally contains only Dart source, docs and assets. The
# Android platform folder (Gradle wrapper, manifest, MainActivity) is
# generated by Flutter itself, so it always matches your installed SDK
# instead of rotting in version control.
#
# `flutter create` will happily overwrite lib/main.dart, README.md and
# pubspec.yaml with its template versions, so this script generates the
# platform files and then restores our sources from git.

set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$PWD"

say()  { printf '\n\033[1;35m==>\033[0m %s\n' "$1"; }
warn() { printf '\033[1;33m[!]\033[0m %s\n' "$1"; }
die()  { printf '\033[1;31m[x]\033[0m %s\n' "$1" >&2; exit 1; }

# ---------------------------------------------------------------- 0. checks
command -v flutter >/dev/null || die "flutter not found in PATH. Install from https://flutter.dev"

FLUTTER_VER="$(flutter --version 2>/dev/null | head -1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1 || echo '0.0.0')"
say "Flutter $FLUTTER_VER"
MAJOR="${FLUTTER_VER%%.*}"
MINOR="$(echo "$FLUTTER_VER" | cut -d. -f2)"
if [ "$MAJOR" -lt 3 ] || { [ "$MAJOR" -eq 3 ] && [ "$MINOR" -lt 24 ]; }; then
  warn "Flutter 3.24+ is recommended (PopScope.onPopInvokedWithResult needs it)."
fi

DIRTY=0
if command -v git >/dev/null && git rev-parse --git-dir >/dev/null 2>&1; then
  if ! git diff --quiet || ! git diff --cached --quiet; then
    DIRTY=1
    warn "You have uncommitted changes. They will be preserved, but"
    warn "flutter create may touch lib/main.dart, pubspec.yaml or README.md."
  fi
else
  warn "Not a git checkout — cannot auto-restore files flutter create overwrites."
fi

# ------------------------------------------------- 1. generate android/ only
if [ -d android ] && [ -f android/app/src/main/AndroidManifest.xml ]; then
  say "android/ already exists — skipping generation"
else
  say "Generating the Android platform folder"

  # Snapshot the files flutter create is known to clobber.
  TMP="$(mktemp -d)"
  for f in lib/main.dart pubspec.yaml README.md analysis_options.yaml; do
    [ -f "$f" ] && { mkdir -p "$TMP/$(dirname "$f")"; cp "$f" "$TMP/$f"; }
  done

  flutter create . \
    --platforms=android \
    --project-name kurayomi \
    --org "${ORG:-com.kurayomi}" \
    --overwrite >/dev/null

  say "Restoring project sources"
  for f in lib/main.dart pubspec.yaml README.md analysis_options.yaml; do
    [ -f "$TMP/$f" ] && cp "$TMP/$f" "$f"
  done
  rm -rf "$TMP"

  # Belt and braces: if git is available and clean, restore everything that
  # is tracked, so nothing template-shaped survives.
  if [ "$DIRTY" -eq 0 ] && git rev-parse --git-dir >/dev/null 2>&1; then
    git checkout -- lib pubspec.yaml README.md analysis_options.yaml 2>/dev/null || true
  fi
fi

# ------------------------------------------- 1b. drop flutter create leftovers
# `flutter create` writes test/widget_test.dart referencing a `MyApp` class
# this project does not have; it fails both analyze and test.
if [ -f test/widget_test.dart ] && grep -q 'MyApp' test/widget_test.dart; then
  rm -f test/widget_test.dart
  echo "   removed the template test/widget_test.dart"
fi

# ---------------------------------------------- 2. Android project configuration
say "Applying Android configuration"
python3 tool/android_patch.py

# ------------------------------------------------------------ 4. dependencies
say "Fetching packages"
flutter pub get

# ------------------------------------------------------------ 5. analyze
say "Analyzing"
if flutter analyze --no-fatal-infos --no-fatal-warnings; then
  printf '\n\033[1;32m✔ Build environment ready.\033[0m\n'
else
  warn "Analyzer reported issues above — see docs/BUILD.md for the common ones."
fi

cat <<'EOF'

Next steps
----------
  flutter devices                 # confirm a device/emulator is attached
  flutter run                     # debug build
  flutter build apk --release     # release APK

Try the demo sources
--------------------
  cd extensions_repo && python3 -m http.server 8080

  then in the app: Browse -> Extensions -> Repositories -> +
    emulator :  http://10.0.2.2:8080/index.json
    device   :  http://<your-lan-ip>:8080/index.json
EOF
